title: step by step
description: >- # this means to ignore newlines until "baseurl:"
  small place
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://claudia1204.github.io"
avatarTitle: claudia
avatarDesc: frontend / python
markdown: kramdown
theme: minima
baidu:
    id: 1e7593df0fda4cc448d5135bc564147c

permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}
    - {title: 标签, description: tags, url: '/tags'}
    - {title: 关于我, description: about, url: '/about'}

# Pagination
plugins: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
